#!/bin/bash
# Assembles the display programs with ca65 (cc65) and writes them into
# C64Core as Swift byte arrays, so the library builds without an assembler.
# CI runs this and fails if the generated file changes: after editing a
# program, run it and commit both.
set -euo pipefail

cd "$(dirname "$0")"
out=../Packages/C64Core/Sources/C64Core/DisplayPrograms.swift
mkdir -p build

{
    echo "// Generated by C64/build.sh from the display programs in C64/. Do not edit."
    echo ""
    echo "/// The display programs, assembled. Each loads at \$0801."
    echo "enum DisplayPrograms {"
    first=1
    for source in viewer.s; do
        name="${source%.s}"
        ca65 --target none -o "build/$name.o" "$source"
        ld65 -C c64.cfg -o "build/$name.bin" "build/$name.o"
        [ "$first" = 1 ] || echo ""
        first=0
        echo "    /// Assembled from C64/$source."
        echo "    static let $name: [UInt8] = ["
        od -An -v -tx1 "build/$name.bin" | tr -s ' ' '\n' | sed '/^$/d' | tr 'a-f' 'A-F' |
            awk '{ printf "%s0x%s,", (NR % 16 == 1 ? "        " : " "), $1 }
                NR % 16 == 0 { printf "\n" }
                END { if (NR % 16 != 0) printf "\n" }'
        echo "    ]"
    done
    echo "}"
} >"$out"
echo "Wrote $out"
